export const getData = () => Promise.resolve({
  articles: [
    {
      "title": "The Power of Artificial Intelligence in Modern Healthcare",
      "image": "https://example.com/images/ai-healthcare.jpg",
      "author": "John Doe",
      "tags": ["Artificial Intelligence", "Healthcare", "Machine Learning"],
      "publicationDate": "2023-07-15T10:30:00Z",
      "readTime": 8,
      "description": "Discover how AI is transforming healthcare with advanced diagnostics and personalized treatment options.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "Exploring the Mysteries of Black Holes",
      "image": "https://example.com/images/black-hole.jpg",
      "author": "Jane Smith",
      "tags": ["Astronomy", "Astrophysics", "Black Holes"],
      "publicationDate": "2023-07-20T09:15:00Z",
      "readTime": 6,
      "description": "Delve into the fascinating world of black holes and their role in the cosmos.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Future of Electric Vehicles: Advancements and Challenges",
      "image": "https://example.com/images/electric-vehicles.jpg",
      "author": "Michael Johnson",
      "tags": ["Electric Vehicles", "Green Technology", "Sustainability"],
      "publicationDate": "2023-07-18T12:45:00Z",
      "readTime": 5,
      "description": "Learn about the latest developments in electric vehicles and the obstacles to mass adoption.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Art of Mindfulness: Enhancing Mental Well-being",
      "image": "https://example.com/images/mindfulness.jpg",
      "author": "Emily Williams",
      "tags": ["Mindfulness", "Mental Health", "Well-being"],
      "publicationDate": "2023-07-22T14:20:00Z",
      "readTime": 7,
      "description": "Explore the practice of mindfulness and its positive effects on mental health and overall well-being.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Rise of Cryptocurrencies: A New Financial Frontier",
      "image": "https://example.com/images/cryptocurrencies.jpg",
      "author": "David Lee",
      "tags": ["Cryptocurrencies", "Blockchain", "Finance"],
      "publicationDate": "2023-07-17T08:10:00Z",
      "readTime": 9,
      "description": "An in-depth look at the revolutionary impact of cryptocurrencies on the global financial landscape.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "Exploring Ancient Civilizations: Unraveling the Secrets of the Past",
      "image": "https://example.com/images/ancient-civilizations.jpg",
      "author": "Sophia Chen",
      "tags": ["History", "Archaeology", "Ancient Civilizations"],
      "publicationDate": "2023-07-19T11:00:00Z",
      "readTime": 6,
      "description": "Journey through time to uncover the mysteries and achievements of ancient civilizations.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Beauty of Underwater Photography: Capturing Marine Life",
      "image": "https://example.com/images/underwater-photography.jpg",
      "author": "Robert Turner",
      "tags": ["Photography", "Marine Life", "Nature"],
      "publicationDate": "2023-07-23T16:00:00Z",
      "readTime": 4,
      "description": "Dive into the mesmerizing world of underwater photography and the wonders of the ocean.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Science Behind Climate Change: Causes and Solutions",
      "image": "https://example.com/images/climate-change.jpg",
      "author": "Elizabeth Wilson",
      "tags": ["Climate Change", "Environment", "Sustainability"],
      "publicationDate": "2023-07-21T13:30:00Z",
      "readTime": 8,
      "description": "An informative analysis of the science, impacts, and strategies to address climate change.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "Beyond Mars: Human Exploration of Outer Planets",
      "image": "https://example.com/images/outer-planets.jpg",
      "author": "William Adams",
      "tags": ["Space Exploration", "Planets", "Astronomy"],
      "publicationDate": "2023-07-16T10:00:00Z",
      "readTime": 7,
      "description": "Unraveling the possibilities of sending human missions to explore the distant planets of our solar system.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    },
    {
      "title": "The Art of Sustainable Architecture: Designing for a Greener Future",
      "image": "https://example.com/images/sustainable-architecture.jpg",
      "author": "Olivia Johnson",
      "tags": ["Architecture", "Sustainability", "Green Building"],
      "publicationDate": "2023-07-24T15:45:00Z",
      "readTime": 6,
      "description": "A deep dive into the principles and innovations of sustainable architecture for a more eco-friendly world.",
      "url": "https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/?utm_source=pocket_saves",
    }
  ],
  tags: [
    "Artificial Intelligence",
    "Healthcare",
    "Machine Learning",
    "Astronomy",
    "Astrophysics",
    "Black Holes",
    "Electric Vehicles",
    "Green Technology",
    "Sustainability",
    "Mindfulness",
    "Mental Health",
    "Well-being",
    "Cryptocurrencies",
    "Blockchain",
    "Finance",
    "History",
    "Archaeology",
    "Ancient Civilizations",
    "Photography",
    "Marine Life",
    "Nature",
    "Climate Change",
    "Environment",
    "Space Exploration",
    "Planets",
    "Architecture",
    "Green Building"
  ]
})